export type ActivityDetail = {
  id: string
  title: string
  location: string
  date: string
  bookedGuests: number
  flag?: string
  host: string
  hostImage: string
  image: string
  price: number
  rating: number
  reviews: number
  duration: string
  maxGuests: number
  category: string
  shortDescription: string
  longDescription: string
  highlights: string[]
  itinerary: string[]
  includes: string[]
  meetingPoint: string
  language: string
  level: string
}

export const activitiesData: Record<string, ActivityDetail> = {
  "1": {
    id: "1",
    title: "Atelier poterie traditionnelle",
    location: "Marrakech, Maroc",
    date: "Samedi 18 mai",
    bookedGuests: 3,
    flag: "🇲🇦",
    host: "Ahmed",
    hostImage: "/moroccan-man-artisan-smiling-portrait.jpg",
    image: "/pottery-workshop-morocco-traditional-crafts-hands-.jpg",
    price: 35,
    rating: 4.9,
    reviews: 127,
    duration: "3h",
    maxGuests: 6,
    category: "Artisanat",
    shortDescription: "Apprenez l'art ancestral de la poterie marocaine dans un atelier familial de la médina.",
    longDescription:
      "Ahmed perpétue la tradition depuis trois générations. Dans son atelier niché au cœur de la médina, il vous guide étape par étape : choix de l'argile, modelage, décoration et cuisson. Vous repartez avec votre création et les techniques pour continuer chez vous.",
    highlights: ["Découverte des outils traditionnels", "Décor sur faïence et calligraphie", "Thé à la menthe et pâtisseries"],
    itinerary: ["Accueil et présentation de l'atelier", "Démonstration et exercices guidés", "Décoration et finitions", "Cuisson et dégustation de thé"],
    includes: ["Matériel et argile", "Boisson d'accueil", "Votre pièce emballée"],
    meetingPoint: "Atelier d'Ahmed, Rue des potiers - Médina",
    language: "Français / Arabe / Anglais",
    level: "Ouvert à tous",
  },
  "2": {
    id: "2",
    title: "Randonnée et pique-nique local",
    location: "Cinque Terre, Italie",
    date: "Dimanche 19 mai",
    bookedGuests: 5,
    flag: "🇮🇹",
    host: "Lucia",
    hostImage: "/italian-woman-hiking-guide-smiling.jpg",
    image: "/hiking-cinque-terre-italy-coastal-view-picnic-natu.jpg",
    price: 55,
    rating: 4.8,
    reviews: 89,
    duration: "5h",
    maxGuests: 8,
    category: "Nature",
    shortDescription: "Randonnez sur les sentiers côtiers avant de savourer un pique-nique préparé avec des produits locaux.",
    longDescription:
      "Lucia connaît chaque terrasse et vignoble suspendu entre ciel et mer. Elle vous emmène sur les plus beaux sentiers, partage les histoires des pêcheurs et installe un pique-nique généreux avec focaccia, pesto et vins sciachetrà.",
    highlights: ["Points de vue privés", "Dégustation de produits artisans", "Conseils photo par Lucia"],
    itinerary: ["Départ de Vernazza", "Randonnée panoramique (2h30)", "Pique-nique et temps libre", "Retour en train local"],
    includes: ["Guide local certifié", "Pique-nique complet", "Billet de train retour"],
    meetingPoint: "Gare de Vernazza",
    language: "Italien / Anglais",
    level: "Bon marcheur",
  },
  "3": {
    id: "3",
    title: "Cours de flamenco intimiste",
    location: "Séville, Espagne",
    date: "Vendredi 24 mai",
    bookedGuests: 2,
    flag: "🇪🇸",
    host: "Isabel",
    hostImage: "/friendly-woman-portrait-smiling.jpg",
    image: "/travel-experience-adventure-colorful.jpg",
    price: 60,
    rating: 4.9,
    reviews: 142,
    duration: "2h30",
    maxGuests: 8,
    category: "Culture",
    shortDescription:
      "Découvrez les bases du flamenco gitan dans un tablao familial et assistez à une performance privée avec musiciens.",
    longDescription:
      "Isabel transmet l'histoire du flamenco andalou avant de vous guider sur les palmas, le compás et les premières passes. La session se termine autour d'un verre de xérès et d'un mini-spectacle avec sa troupe, pour ressentir l'énergie brute des tablaos sévillans.",
    highlights: [
      "Mini spectacle avec guitare et chant en direct",
      "Initiation aux palmas et rythmes gitans",
      "Dégustation de xérès artisanal",
    ],
    itinerary: [
      "Accueil dans le tablao d'Isabel",
      "Atelier mouvement & rythme",
      "Session pratique en groupe",
      "Performance privée + dégustation",
    ],
    includes: ["Cours complet", "Boisson locale", "Photos et vidéos"],
    meetingPoint: "Tablao El Arenal, Séville",
    language: "Espagnol / Français / Anglais",
    level: "Débutant accepté",
  },
  "4": {
    id: "4",
    title: "Tapas & marché de la Boqueria",
    location: "Barcelone, Espagne",
    date: "Jeudi 23 mai",
    bookedGuests: 4,
    flag: "🇪🇸",
    host: "Javier",
    hostImage: "/german-man-backpacker-smiling-portrait.jpg",
    image: "/happy-travelers-sharing-meal-with-local-host-famil.jpg",
    price: 48,
    rating: 4.8,
    reviews: 168,
    duration: "3h30",
    maxGuests: 10,
    category: "Gastronomie",
    shortDescription: "Explorez la Boqueria, choisissez vos produits et préparez trois tapas signature dans l'atelier de Javier.",
    longDescription:
      "Ancien chef de bodega, Javier vous emmène vers ses stands favoris pour goûter jambon ibérique, fruits de mer et huiles catalanes. Direction ensuite sa cuisine pour élaborer bombas, pan con tomate twisté et pintxos de saison accompagnés d'un vermouth maison.",
    highlights: [
      "Sélection de 8 dégustations sur le marché",
      "Atelier tapas mains dans la pâte",
      "Vermouth artisanal inclus",
    ],
    itinerary: [
      "Tour guidé de la Boqueria",
      "Achat d'ingrédients avec Javier",
      "Atelier cuisine dans la casa GOYAGE",
      "Dégustation conviviale et pairing vermouth",
    ],
    includes: ["Dégustations marché", "Ingrédients atelier", "Deux verres de vermouth"],
    meetingPoint: "Entrée principale de la Boqueria",
    language: "Espagnol / Anglais / Français",
    level: "Tous niveaux",
  },
  "5": {
    id: "5",
    title: "Atelier cuisine balinaise chez Kadek",
    location: "Ubud, Bali",
    date: "Mardi 21 mai",
    bookedGuests: 6,
    flag: "🇮🇩",
    host: "Kadek",
    hostImage: "/friendly-woman-portrait-smiling.jpg",
    image: "/bali-rice-terraces-temple-spiritual.jpg",
    price: 58,
    rating: 4.9,
    reviews: 152,
    duration: "4h",
    maxGuests: 8,
    category: "Gastronomie",
    shortDescription: "Visitez un marché matinal puis préparez un menu balinais complet dans la cuisine ouverte de Kadek.",
    longDescription:
      "Kadek vous enseigne les bases du bumbu bali, la cuisson au feu de bois et le dressage traditionnel. Après le marché, vous cuisiner plusieurs plats iconiques (sate lilit, lawar, desserts à la noix de coco) que vous dégustez dans le jardin familial.",
    highlights: [
      "Visite guidée du marché d'Ubud",
      "Préparation du bumbu bali au mortier",
      "Recettes imprimées et adaptables",
    ],
    itinerary: [
      "Rencontre au marché traditionnel",
      "Sélection d'ingrédients et dégustations",
      "Atelier cuisine chez Kadek",
      "Déjeuner dans le jardin",
    ],
    includes: ["Transfert marché -> maison", "Ingrédients", "Déjeuner + boissons"],
    meetingPoint: "Statue de Saraswati, marché d'Ubud",
    language: "Indonésien / Anglais",
    level: "Gourmet curieux",
  },
  "6": {
    id: "6",
    title: "Snorkeling tortues & coraux",
    location: "Praslin, Seychelles",
    date: "Lundi 27 mai",
    bookedGuests: 2,
    flag: "🇸🇨",
    host: "Aline",
    hostImage: "/friendly-woman-portrait-smiling.jpg",
    image: "/tortue.png",
    price: 75,
    rating: 4.9,
    reviews: 101,
    duration: "3h30",
    maxGuests: 6,
    category: "Nature",
    shortDescription: "Explorez les récifs de Curieuse avec une guide naturaliste et nagez parmi les tortues et raies inoffensives.",
    longDescription:
      "Aline, biologiste marine, vous emmène en pirogue traditionnelle vers les meilleurs spots. Briefing sécurité, prêt d'équipement premium et focus sur la protection des coraux vous garantissent une immersion durable.",
    highlights: [
      "Observation garantie des tortues vertes",
      "Guide biologiste francophone",
      "Encas fruits exotiques sur la plage",
    ],
    itinerary: [
      "Briefing et équipement à Anse Volbert",
      "Navigation vers Curieuse",
      "Deux sessions snorkeling guidées",
      "Pause fruits & sensibilisation environnement",
    ],
    includes: ["Matériel complet", "Transfert bateau", "Encas & boissons"],
    meetingPoint: "Cabane GOYAGE, Anse Volbert",
    language: "Français / Anglais / Créole",
    level: "À l'aise dans l'eau",
  },
  "7": {
    id: "7",
    title: "Yoga sunrise sur la plage",
    location: "Canggu, Bali",
    date: "Chaque matin à 6h",
    bookedGuests: 7,
    flag: "🇮🇩",
    host: "Made",
    hostImage: "/placeholder-user.jpg",
    image: "/yoga.png",
    price: 25,
    rating: 4.9,
    reviews: 231,
    duration: "1h30",
    maxGuests: 12,
    category: "Bien-être",
    shortDescription: "Séance sunrise yoga Vinyasa suivie d’un smoothie bowl sur la plage secrète de Made.",
    longDescription:
      "Made adapte la pratique (vinyasa doux) au niveau des participants et partage des exercices de respiration balinais. Après la séance, place à un jus frais et un cercle de discussions.",
    highlights: ["Prêt de tapis et serviette", "Techniques de respiration", "Playlist détente GOYAGE"],
    itinerary: ["Méditation guidée", "Séquence vinyasa", "Relaxation sonore", "Jus detox"],
    includes: ["Matériel", "Boisson fraîche", "Photos souvenirs"],
    meetingPoint: "Plage de Sanur, cabane GOYAGE",
    language: "Anglais / Indonésien",
    level: "Tous niveaux",
  },
  "8": {
    id: "8",
    title: "Atelier pasta & mercato Testaccio",
    location: "Rome, Italie",
    date: "Mercredi 22 mai",
    bookedGuests: 4,
    flag: "🇮🇹",
    host: "Giulia",
    hostImage: "/italian-woman-hiking-guide-smiling.jpg",
    image: "/italy-tuscany-vineyard-sunset-romantic.jpg",
    price: 62,
    rating: 4.8,
    reviews: 134,
    duration: "4h",
    maxGuests: 10,
    category: "Gastronomie",
    shortDescription: "Visitez le mercato Testaccio puis réalisez pasta fresca et tiramisu avec Giulia dans son loft.",
    longDescription:
      "Giulia sélectionne pour vous farines artisanales, pecorino romano et herbes fraîches. Vous réalisez tagliolini, ravioli farcis et un tiramisu revisité tout en découvrant l'histoire culinaire romaine.",
    highlights: [
      "Visite guidée du marché Testaccio",
      "Techniques pasta fresca pas à pas",
      "Accords vins naturels du Latium",
    ],
    itinerary: [
      "Rencontre au marché et dégustations",
      "Achat des ingrédients",
      "Atelier pasta & dessert",
      "Repas autour de la grande table de Giulia",
    ],
    includes: ["Ingrédients premium", "Vin naturel", "Carnet de recettes"],
    meetingPoint: "Entrée principale Mercato Testaccio",
    language: "Italien / Anglais",
    level: "Tous niveaux",
  },
}
