export type BoxExperience = {
  id: string
  title: string
  description: string
  image: string
  duration: string
  location: string
  host: string
  hostImage: string
  rating: number
}

export type BoxHost = {
  id: string
  name: string
  role: string
  image: string
  rating: number
  reviews: number
  bio: string
  languages: string[]
}

export type BoxData = {
  id: string
  name: string
  country: string
  flag: string
  image: string
  rating: number
  reviews: number
  experiencesCount: number
  description: string
  longDescription: string
  price: number
  originalPrice: number
  experiences: BoxExperience[]
  hosts: BoxHost[]
  tag?: string
  tagColor?: string
}

export const boxesData: Record<string, BoxData> = {
  "maroc-authentique": {
    id: "maroc-authentique",
    name: "Box Maroc Authentique",
    country: "Maroc",
    flag: "🇲🇦",
    image: "/maroc.png",
    rating: 4.9,
    reviews: 234,
    experiencesCount: 4,
    description: "Plongez dans la magie du Maroc",
    longDescription:
      "Découvrez le Maroc authentique à travers 4 expériences uniques avec nos hôtes. De la poterie dans la médina à un thé chez l'habitant, la box vous embarque dans un carnet d'adresses exclusif au cœur de Marrakech et de l'Atlas.",
    price: 149,
    originalPrice: 189,
    tag: "Best-seller",
    tagColor: "bg-coral",
    experiences: [
      {
        id: "maroc-exp-1",
        title: "Atelier poterie dans la médina",
        description: "Modelez et décorez votre pièce dans un atelier familial ancestral.",
        image: "/pottery-workshop-morocco-traditional-crafts-hands-.jpg",
        duration: "3h",
        location: "Médina de Marrakech",
        host: "Ahmed",
        hostImage: "/moroccan-man-artisan-smiling-portrait.jpg",
        rating: 4.9,
      },
      {
        id: "maroc-exp-2",
        title: "Cours de cuisine dans un riad",
        description: "Préparez un tajine et dégustez-le sur la terrasse d'un riad secret.",
        image: "/maroc.png",
        duration: "4h",
        location: "Riad familial",
        host: "Fatima",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 5,
      },
      {
        id: "maroc-exp-3",
        title: "Balade guidée dans les souks",
        description: "Découvrez les artisans et les meilleures adresses cachées.",
        image: "/maroc.png",
        duration: "2h30",
        location: "Souks de Marrakech",
        host: "Youssef",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.8,
      },
      {
        id: "maroc-exp-4",
        title: "Thé et pâtisseries chez l'habitant",
        description: "Partagez un moment de convivialité autour d'un goûter traditionnel.",
        image: "/maroc.png",
        duration: "1h30",
        location: "Maison traditionnelle",
        host: "Khadija",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 5,
      },
    ],
    hosts: [
      {
        id: "host-maroc-1",
        name: "Ahmed",
        role: "Maître potier",
        image: "/moroccan-man-artisan-smiling-portrait.jpg",
        rating: 4.9,
        reviews: 127,
        bio: "Potier depuis 3 générations, Ahmed perpétue la tradition familiale au cœur de la médina.",
        languages: ["Français", "Arabe", "Anglais"],
      },
      {
        id: "host-maroc-2",
        name: "Fatima",
        role: "Cheffe cuisinière",
        image: "/friendly-woman-portrait-smiling.jpg",
        rating: 5,
        reviews: 89,
        bio: "Fatima partage les secrets de la cuisine marocaine transmis par sa grand-mère.",
        languages: ["Français", "Arabe"],
      },
      {
        id: "host-maroc-3",
        name: "Youssef",
        role: "Guide local",
        image: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.8,
        reviews: 156,
        bio: "Né et grandi dans la médina, Youssef connaît chaque ruelle et chaque artisan.",
        languages: ["Français", "Arabe", "Anglais", "Espagnol"],
      },
    ],
  },
  "italie-dolce-vita": {
    id: "italie-dolce-vita",
    name: "Box Italie Dolce Vita",
    country: "Italie",
    flag: "🇮🇹",
    image: "/italy-tuscany-vineyard-sunset-romantic.jpg",
    rating: 4.8,
    reviews: 312,
    experiencesCount: 4,
    description: "La dolce vita italienne en 4 expériences",
    longDescription:
      "Vibrez aux couleurs italiennes entre cours de pasta fresca, dégustations de vins naturels et escapades romantiques dans les ruelles des Cinque Terre et de Rome.",
    price: 179,
    originalPrice: 219,
    tag: "Romantique",
    tagColor: "bg-pink",
    experiences: [
      {
        id: "italie-exp-1",
        title: "Cours de pasta fresca à Rome",
        description: "Réalisez tagliolini et ravioli aux côtés de Giulia dans son loft.",
        image: "/italy-tuscany-vineyard-sunset-romantic.jpg",
        duration: "4h",
        location: "Rome",
        host: "Giulia",
        hostImage: "/italian-woman-hiking-guide-smiling.jpg",
        rating: 4.9,
      },
      {
        id: "italie-exp-2",
        title: "Randonnée panoramique Cinque Terre",
        description: "Marchez de village en village avec des pauses focaccia & pesto.",
        image: "/hiking-cinque-terre-italy-coastal-view-picnic-natu.jpg",
        duration: "5h",
        location: "Cinque Terre",
        host: "Lucia",
        hostImage: "/italian-woman-hiking-guide-smiling.jpg",
        rating: 4.8,
      },
      {
        id: "italie-exp-3",
        title: "Dégustation de vins toscans",
        description: "Visitez un domaine familial et goûtez aux crus biologiques.",
        image: "/italy-tuscany-vineyard-sunset-romantic.jpg",
        duration: "3h",
        location: "Toscane",
        host: "Marco",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.9,
      },
      {
        id: "italie-exp-4",
        title: "Tour en vespa vintage",
        description: "Ride guidé dans Rome avec arrêts cafés et gelato artisanaux.",
        image: "/italy-tuscany-vineyard-sunset-romantic.jpg",
        duration: "2h",
        location: "Rome",
        host: "Enzo",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.7,
      },
    ],
    hosts: [
      {
        id: "host-italie-1",
        name: "Giulia",
        role: "Cheffe & food stylist",
        image: "/friendly-woman-portrait-smiling.jpg",
        rating: 5,
        reviews: 154,
        bio: "Giulia cuisine les recettes de sa nonna et anime des ateliers conviviaux à Rome.",
        languages: ["Italien", "Anglais"],
      },
      {
        id: "host-italie-2",
        name: "Lucia",
        role: "Guide randonnée",
        image: "/italian-woman-hiking-guide-smiling.jpg",
        rating: 4.9,
        reviews: 132,
        bio: "Guide certifiée, Lucia connaît les sentiers secrets suspendus entre mer et vignes.",
        languages: ["Italien", "Anglais", "Français"],
      },
      {
        id: "host-italie-3",
        name: "Marco",
        role: "Sommelier",
        image: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.8,
        reviews: 98,
        bio: "Marco produit des vins naturels dans le Latium et adore partager son terroir.",
        languages: ["Italien", "Anglais"],
      },
    ],
  },
  "bali-spirituel": {
    id: "bali-spirituel",
    name: "Box Bali Spirituel",
    country: "Indonésie",
    flag: "🇮🇩",
    image: "/bali-rice-terraces-temple-spiritual.jpg",
    rating: 4.9,
    reviews: 156,
    experiencesCount: 5,
    description: "Reconnectez-vous avec vous-même à Bali",
    longDescription:
      "Entre retraites yoga, cuisine balinaise et cérémonies de purification, cette box vous ouvre les portes de l'île des Dieux avec nos hôtes Kadek, Made et Gusti.",
    price: 159,
    originalPrice: 199,
    tag: "Bien-être",
    tagColor: "bg-green",
    experiences: [
      {
        id: "bali-exp-1",
        title: "Atelier cuisine balinaise",
        description: "Visite du marché et réalisation d'un menu complet dans un jardin familial.",
        image: "/bali-rice-terraces-temple-spiritual.jpg",
        duration: "4h",
        location: "Ubud",
        host: "Kadek",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.9,
      },
      {
        id: "bali-exp-2",
        title: "Yoga sunrise sur la plage",
        description: "Séance Vinyasa face à l'océan suivie d'un smoothie bowl coloré.",
        image: "/yoga.png",
        duration: "1h30",
        location: "Canggu",
        host: "Made",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.9,
      },
      {
        id: "bali-exp-3",
        title: "Cérémonie de purification",
        description: "Rituel guidé dans les eaux sacrées de Tirta Empul.",
        image: "/bali-rice-temple.png",
        duration: "3h",
        location: "Tirta Empul",
        host: "Gusti",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.8,
      },
      {
        id: "bali-exp-4",
        title: "Massage balinais traditionnel",
        description: "Soin relaxant dans une maison familiale entourée de rizières.",
        image: "/bali-rice-terraces-temple-spiritual.jpg",
        duration: "1h",
        location: "Ubud",
        host: "Putri",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 5,
      },
      {
        id: "bali-exp-5",
        title: "Balade dans les rizières de Tegallalang",
        description: "Découverte des systèmes d'irrigation subak et rencontre des fermiers.",
        image: "/bali-rice-terraces-temple-spiritual.jpg",
        duration: "2h30",
        location: "Tegallalang",
        host: "Komang",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.7,
      },
    ],
    hosts: [
      {
        id: "host-bali-1",
        name: "Kadek",
        role: "Cheffe & hôte",
        image: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.9,
        reviews: 152,
        bio: "Kadek cuisine dans son jardin tropical et adore transmettre les secrets du bumbu bali.",
        languages: ["Indonésien", "Anglais"],
      },
      {
        id: "host-bali-2",
        name: "Made",
        role: "Professeure de yoga",
        image: "/friendly-woman-portrait-smiling.jpg",
        rating: 5,
        reviews: 231,
        bio: "Made crée des expériences sunrise yoga intimistes sur des plages secrètes.",
        languages: ["Indonésien", "Anglais"],
      },
      {
        id: "host-bali-3",
        name: "Gusti",
        role: "Guide spirituel",
        image: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.8,
        reviews: 118,
        bio: "Gusti accompagne les visiteurs lors des rituels de purification depuis son enfance.",
        languages: ["Indonésien", "Anglais"],
      },
    ],
  },
  "espagne-vibrante": {
    id: "espagne-vibrante",
    name: "Box Espagne Vibrante",
    country: "Espagne",
    flag: "🇪🇸",
    image: "/mediterranean-sea-coastal-village-sunset.jpg",
    rating: 4.8,
    reviews: 210,
    experiencesCount: 4,
    description: "Tapas, flamenco et couchers de soleil",
    longDescription:
      "Des ruelles de Séville aux marchés de Barcelone, cette box rassemble le meilleur de l'Espagne : ateliers tapas, cours de flamenco et sorties en voilier au coucher du soleil.",
    price: 159,
    originalPrice: 199,
    tag: "Culture & fiesta",
    tagColor: "bg-coral",
    experiences: [
      {
        id: "espagne-exp-1",
        title: "Tapas & marché de la Boqueria",
        description: "Course au marché puis atelier tapas dans la casa GOYAGE.",
        image: "/happy-travelers-sharing-meal-with-local-host-famil.jpg",
        duration: "3h30",
        location: "Barcelone",
        host: "Javier",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.8,
      },
      {
        id: "espagne-exp-2",
        title: "Cours de flamenco intimiste",
        description: "Initiez-vous dans un tablao familial avec musique live.",
        image: "/travel-experience-adventure-colorful.jpg",
        duration: "2h30",
        location: "Séville",
        host: "Isabel",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.9,
      },
      {
        id: "espagne-exp-3",
        title: "Voilier sunset vers les criques",
        description: "Navigation privatisée autour des Baléares avec tapas à bord.",
        image: "/mediterranean-sea-coastal-village-sunset.jpg",
        duration: "3h",
        location: "Palma",
        host: "Raul",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.9,
      },
      {
        id: "espagne-exp-4",
        title: "Atelier guitare flamenca",
        description: "Rencontrez un luthier et apprenez les bases du compás.",
        image: "/travel-experience-adventure-colorful.jpg",
        duration: "2h",
        location: "Cadix",
        host: "Paco",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.7,
      },
    ],
    hosts: [
      {
        id: "host-espagne-1",
        name: "Javier",
        role: "Chef & guide food",
        image: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.8,
        reviews: 168,
        bio: "Ancien chef de bodega, Javier connaît chaque stand de la Boqueria.",
        languages: ["Espagnol", "Anglais", "Français"],
      },
      {
        id: "host-espagne-2",
        name: "Isabel",
        role: "Danseuse flamenco",
        image: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.9,
        reviews: 142,
        bio: "Isabel dirige un tablao familial où elle initie aux palmas et compás.",
        languages: ["Espagnol", "Français", "Anglais"],
      },
      {
        id: "host-espagne-3",
        name: "Raul",
        role: "Skipper & musicien",
        image: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.8,
        reviews: 95,
        bio: "Raul organise des sunsets en voilier avec tapas maison.",
        languages: ["Espagnol", "Anglais"],
      },
    ],
  },
  "seychelles-evasion": {
    id: "seychelles-evasion",
    name: "Box Seychelles Évasion",
    country: "Seychelles",
    flag: "🇸🇨",
    image: "/seychelles.png",
    rating: 4.9,
    reviews: 128,
    experiencesCount: 4,
    description: "Lagons turquoise et art de vivre créole",
    longDescription:
      "Nagez avec les tortues, cuisinez créole et profitez de couchers de soleil en catamaran. Cette box vous emmène sur Mahé, Praslin et La Digue avec nos hôtes biologistes et chefs.",
    price: 189,
    originalPrice: 229,
    tag: "Îles paradisiaques",
    tagColor: "bg-green",
    experiences: [
      {
        id: "seychelles-exp-1",
        title: "Snorkeling tortues & coraux",
        description: "Session guidée par une biologiste marine dans les réserves protégées.",
        image: "/seychelles.png",
        duration: "3h30",
        location: "Praslin",
        host: "Aline",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.9,
      },
      {
        id: "seychelles-exp-2",
        title: "Atelier cuisine créole",
        description: "Apprenez à préparer cari coco et chutneys d'inspiration locale.",
        image: "/seychelles.png",
        duration: "3h",
        location: "Mahé",
        host: "Vanessa",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.8,
      },
      {
        id: "seychelles-exp-3",
        title: "Croisière sunset en catamaran",
        description: "Naviguez au coucher du soleil avec musique sega et cocktails.",
        image: "/seychelles.png",
        duration: "2h30",
        location: "La Digue",
        host: "David",
        hostImage: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.9,
      },
      {
        id: "seychelles-exp-4",
        title: "Balade coco-de-mer",
        description: "Exploration guidée du parc de la Vallée de Mai.",
        image: "/seychelles.png",
        duration: "2h",
        location: "Praslin",
        host: "Lorna",
        hostImage: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.7,
      },
    ],
    hosts: [
      {
        id: "host-seychelles-1",
        name: "Aline",
        role: "Biologiste marine",
        image: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.9,
        reviews: 101,
        bio: "Aline protège les récifs seychellois et anime des sorties snorkeling intimistes.",
        languages: ["Français", "Anglais", "Créole"],
      },
      {
        id: "host-seychelles-2",
        name: "Vanessa",
        role: "Cheffe créole",
        image: "/friendly-woman-portrait-smiling.jpg",
        rating: 4.8,
        reviews: 64,
        bio: "Vanessa partage les recettes de sa famille sur Mahé autour d'une grande table colorée.",
        languages: ["Français", "Anglais"],
      },
      {
        id: "host-seychelles-3",
        name: "David",
        role: "Skipper catamaran",
        image: "/german-man-backpacker-smiling-portrait.jpg",
        rating: 4.9,
        reviews: 83,
        bio: "David organise des croisières sunset rythmées de musique sega.",
        languages: ["Français", "Anglais"],
      },
    ],
  },
}

export const boxesList = Object.values(boxesData)
